const weapons = [
  { display: "わかばシューター", path: "./images/わかばシューター.png" },
  { display: "N-ZAP89", path: "./images/N-ZAP89.png" },
  { display: "スプラシューター", path: "./images/スプラシューター.png" },
  { display: "もみじシューター", path: "./images/もみじシューター.png" },
  {
    display: "オーダーシューター レプリカ",
    path: "./images/オーダーシューター レプリカ.png",
  },
  {
    display: "ヒーローシューター レプリカ",
    path: "./images/ヒーローシューター レプリカ.png",
  },
  { display: "N-ZAP85", path: "./images/N-ZAP85.png" },
  {
    display: "スプラシューターコラボ",
    path: "./images/スプラシューターコラボ.png",
  },
  { display: "スペースシューター", path: "./images/スペースシューター.png" },
  {
    display: "シャープマーカーネオ",
    path: "./images/シャープマーカーネオ.png",
  },
  { display: "プロモデラー彩", path: "./images/プロモデラー彩.png" },
  { display: "プロモデラーMG", path: "./images/プロモデラーMG.png" },
  { display: "スプラシューター煌", path: "./images/スプラシューター煌.png" },
  { display: "プロモデラーRG", path: "./images/プロモデラーRG.png" },
  { display: "ボールドマーカー", path: "./images/ボールドマーカー.png" },
  {
    display: "ボールドマーカーネオ",
    path: "./images/ボールドマーカーネオ.png",
  },
  { display: "52ガロンデコ", path: "./images/52ガロンデコ.png" },
  { display: "96ガロン", path: "./images/96ガロン.png" },
  { display: "52ガロン", path: "./images/52ガロン.png" },
  { display: "シャープマーカー", path: "./images/シャープマーカー.png" },
  {
    display: "シャープマーカーGECK",
    path: "./images/シャープマーカーGECK.png",
  },
  { display: "96ガロン爪", path: "./images/96ガロン爪.png" },
  { display: "96ガロンデコ", path: "./images/96ガロンデコ.png" },
  { display: "H3リールガンSNAK", path: "./images/H3リールガンSNAK.png" },
  { display: "L3リールガン", path: "./images/L3リールガン.png" },
  {
    display: "プライムシューターFRZN",
    path: "./images/プライムシューターFRZN.png",
  },
  { display: "L3リールガンD", path: "./images/L3リールガンD.png" },
  { display: "ジェットスイーパー", path: "./images/ジェットスイーパー.png" },
  { display: "ボトルガイザー", path: "./images/ボトルガイザー.png" },
  { display: "L3リールガン箔", path: "./images/L3リールガン箔.png" },
  {
    display: "ボトルガイザーフォイル",
    path: "./images/ボトルガイザーフォイル.png",
  },
  { display: "H3リールガン", path: "./images/H3リールガン.png" },
  {
    display: "スペースシューターコラボ",
    path: "./images/スペースシューターコラボ.png",
  },
  { display: "プライムシューター", path: "./images/プライムシューター.png" },
  {
    display: "オーダーローラー レプリカ",
    path: "./images/オーダーローラー レプリカ.png",
  },
  { display: "H3リールガンD", path: "./images/H3リールガンD.png" },
  {
    display: "スプラローラーコラボ",
    path: "./images/スプラローラーコラボ.png",
  },
  {
    display: "カーボンローラーデコ",
    path: "./images/カーボンローラーデコ.png",
  },
  {
    display: "ジェットスイーパーカスタム",
    path: "./images/ジェットスイーパーカスタム.png",
  },
  { display: "スプラローラー", path: "./images/スプラローラー.png" },
  { display: "ダイナモローラー", path: "./images/ダイナモローラー.png" },
  { display: "カーボンローラー", path: "./images/カーボンローラー.png" },
  {
    display: "ヴァリアブルローラーフォイル",
    path: "./images/ヴァリアブルローラーフォイル.png",
  },
  {
    display: "ダイナモローラーテスラ",
    path: "./images/ダイナモローラーテスラ.png",
  },
  {
    display: "ヴァリアブルローラー",
    path: "./images/ヴァリアブルローラー.png",
  },
  {
    display: "プライムシューターコラボ",
    path: "./images/プライムシューターコラボ.png",
  },
  {
    display: "ジェットスイーパーCOBR",
    path: "./images/ジェットスイーパーCOBR.png",
  },
  {
    display: "カーボンローラーANGL",
    path: "./images/カーボンローラーANGL.png",
  },
  {
    display: "ワイドローラーコラボ",
    path: "./images/ワイドローラーコラボ.png",
  },
  { display: "ワイドローラー", path: "./images/ワイドローラー.png" },
  { display: "ドライブワイパー", path: "./images/ドライブワイパー.png" },
  { display: "ダイナモローラー冥", path: "./images/ダイナモローラー冥.png" },
  { display: "ワイドローラー惑", path: "./images/ワイドローラー惑.png" },
  {
    display: "オーダーワイパー レプリカ",
    path: "./images/オーダーワイパー レプリカ.png",
  },
  {
    display: "デンタルワイパーミント",
    path: "./images/デンタルワイパーミント.png",
  },
  { display: "ジムワイパー封", path: "./images/ジムワイパー封.png" },
  { display: "パブロ", path: "./images/パブロ.png" },
  {
    display: "ドライブワイパーデコ",
    path: "./images/ドライブワイパーデコ.png",
  },
  { display: "ジムワイパー", path: "./images/ジムワイパー.png" },
  {
    display: "ドライブワイパーRUST",
    path: "./images/ドライブワイパーRUST.png",
  },
  {
    display: "ジムワイパー・ヒュー",
    path: "./images/ジムワイパー・ヒュー.png",
  },
  { display: "パブロ・ヒュー", path: "./images/パブロ・ヒュー.png" },
  {
    display: "デンタルワイパースミ",
    path: "./images/デンタルワイパースミ.png",
  },
  { display: "ホクサイ", path: "./images/ホクサイ.png" },
  { display: "フィンセントBRNZ", path: "./images/フィンセントBRNZ.png" },
  { display: "ホクサイ彗", path: "./images/ホクサイ彗.png" },
  {
    display: "オーダーブラシ レプリカ",
    path: "./images/オーダーブラシ レプリカ.png",
  },
  {
    display: "フィンセント・ヒュー",
    path: "./images/フィンセント・ヒュー.png",
  },
  { display: "ホクサイ・ヒュー", path: "./images/ホクサイ・ヒュー.png" },
  { display: "ホットブラスター", path: "./images/ホットブラスター.png" },
  { display: "ホットブラスター艶", path: "./images/ホットブラスター艶.png" },
  { display: "フィンセント", path: "./images/フィンセント.png" },
  {
    display: "ホットブラスターカスタム",
    path: "./images/ホットブラスターカスタム.png",
  },
  {
    display: "ロングブラスターカスタム",
    path: "./images/ロングブラスターカスタム.png",
  },
  {
    display: "ノヴァブラスターネオ",
    path: "./images/ノヴァブラスターネオ.png",
  },
  {
    display: "クラッシュブラスターネオ",
    path: "./images/クラッシュブラスターネオ.png",
  },
  {
    display: "オーダーブラスター レプリカ",
    path: "./images/オーダーブラスター レプリカ.png",
  },
  { display: "ノヴァブラスター", path: "./images/ノヴァブラスター.png" },
  {
    display: "バケットスロッシャー",
    path: "./images/バケットスロッシャー.png",
  },
  { display: "S-BLAST91", path: "./images/S-BLAST91.png" },
  {
    display: "Rブラスターエリートデコ",
    path: "./images/Rブラスターエリートデコ.png",
  },
  {
    display: "バケットスロッシャーデコ",
    path: "./images/バケットスロッシャーデコ.png",
  },
  { display: "Rブラスターエリート", path: "./images/Rブラスターエリート.png" },
  { display: "ラピッドブラスター", path: "./images/ラピッドブラスター.png" },
  { display: "エクスプロッシャー", path: "./images/エクスプロッシャー.png" },
  { display: "ヒッセン・ヒュー", path: "./images/ヒッセン・ヒュー.png" },
  {
    display: "スクリュースロッシャー",
    path: "./images/スクリュースロッシャー.png",
  },
  {
    display: "オーダースロッシャー レプリカ",
    path: "./images/オーダースロッシャー レプリカ.png",
  },
  { display: "モップリン", path: "./images/モップリン.png" },
  { display: "ヒッセンASH", path: "./images/ヒッセンASH.png" },
  {
    display: "オーバーフロッシャー",
    path: "./images/オーバーフロッシャー.png",
  },
  { display: "モップリン角", path: "./images/モップリン角.png" },
  { display: "スプラマニューバー", path: "./images/スプラマニューバー.png" },
  { display: "ヒッセン", path: "./images/ヒッセン.png" },
  {
    display: "クラッシュブラスター",
    path: "./images/クラッシュブラスター.png",
  },
  { display: "ガエンFFカスタム", path: "./images/ガエンFFカスタム.png" },
  {
    display: "エクスプロッシャーカスタム",
    path: "./images/エクスプロッシャーカスタム.png",
  },
  {
    display: "スパッタリー・ヒュー",
    path: "./images/スパッタリー・ヒュー.png",
  },
  {
    display: "スプラマニューバーコラボ",
    path: "./images/スプラマニューバーコラボ.png",
  },
  {
    display: "スクリュースロッシャーネオ",
    path: "./images/スクリュースロッシャーネオ.png",
  },
  { display: "ケルビン525デコ", path: "./images/ケルビン525デコ.png" },
  { display: "モップリンD", path: "./images/モップリンD.png" },
  {
    display: "デュアルスイーパーカスタム",
    path: "./images/デュアルスイーパーカスタム.png",
  },
  { display: "S-BLAST92", path: "./images/S-BLAST92.png" },
  {
    display: "オーダーマニューバー レプリカ",
    path: "./images/オーダーマニューバー レプリカ.png",
  },
  {
    display: "スプラマニューバー耀",
    path: "./images/スプラマニューバー耀.png",
  },
  { display: "LACT-450デコ", path: "./images/LACT-450デコ.png" },
  {
    display: "オーバーフロッシャーデコ",
    path: "./images/オーバーフロッシャーデコ.png",
  },
  {
    display: "キャンピングシェルターソレーラ",
    path: "./images/キャンピングシェルターソレーラ.png",
  },
  {
    display: "RブラスターエリートWNTR",
    path: "./images/RブラスターエリートWNTR.png",
  },
  { display: "スパッタリーOWL", path: "./images/スパッタリーOWL.png" },
  { display: "ガエンFF", path: "./images/ガエンFF.png" },
  { display: "24式張替傘・甲", path: "./images/24式張替傘・甲.png" },
  { display: "トライストリンガー", path: "./images/トライストリンガー.png" },
  { display: "スパイガジェット繚", path: "./images/スパイガジェット繚.png" },
  { display: "パラシェルター", path: "./images/パラシェルター.png" },
  {
    display: "スプラスピナーコラボ",
    path: "./images/スプラスピナーコラボ.png",
  },
  {
    display: "オーダースピナー レプリカ",
    path: "./images/オーダースピナー レプリカ.png",
  },
  { display: "ケルビン525", path: "./images/ケルビン525.png" },
  { display: "フルイドV", path: "./images/フルイドV.png" },
  { display: "ロングブラスター", path: "./images/ロングブラスター.png" },
  {
    display: "スパイガジェットソレーラ",
    path: "./images/スパイガジェットソレーラ.png",
  },
  { display: "LACT-450", path: "./images/LACT-450.png" },
  {
    display: "オーダーシェルター レプリカ",
    path: "./images/オーダーシェルター レプリカ.png",
  },
  { display: "フルイドVカスタム", path: "./images/フルイドVカスタム.png" },
  { display: "スプラスピナーPYTN", path: "./images/スプラスピナーPYTN.png" },
  {
    display: "クアッドホッパーブラック",
    path: "./images/クアッドホッパーブラック.png",
  },
  { display: "スパイガジェット", path: "./images/スパイガジェット.png" },
  {
    display: "クーゲルシュライバー・ヒュー",
    path: "./images/クーゲルシュライバー・ヒュー.png",
  },
  {
    display: "クアッドホッパーホワイト",
    path: "./images/クアッドホッパーホワイト.png",
  },
  {
    display: "スプラチャージャーFRST",
    path: "./images/スプラチャージャーFRST.png",
  },
  {
    display: "トライストリンガー燈",
    path: "./images/トライストリンガー燈.png",
  },
  { display: "イグザミナー", path: "./images/イグザミナー.png" },
  {
    display: "デュアルスイーパー蹄",
    path: "./images/デュアルスイーパー蹄.png",
  },
  { display: "スプラチャージャー", path: "./images/スプラチャージャー.png" },
  {
    display: "パラシェルターソレーラ",
    path: "./images/パラシェルターソレーラ.png",
  },
  {
    display: "オーダーストリンガー レプリカ",
    path: "./images/オーダーストリンガー レプリカ.png",
  },
  { display: "24式張替傘・乙", path: "./images/24式張替傘・乙.png" },
  {
    display: "キャンピングシェルター",
    path: "./images/キャンピングシェルター.png",
  },
  {
    display: "スプラスコープコラボ",
    path: "./images/スプラスコープコラボ.png",
  },
  {
    display: "ラピッドブラスターデコ",
    path: "./images/ラピッドブラスターデコ.png",
  },
  {
    display: "トライストリンガーコラボ",
    path: "./images/トライストリンガーコラボ.png",
  },
  {
    display: "キャンピングシェルターCREM",
    path: "./images/キャンピングシェルターCREM.png",
  },
  { display: "スパッタリー", path: "./images/スパッタリー.png" },
  { display: "LACT-450MILK", path: "./images/LACT-450MILK.png" },
  { display: "ハイドラント圧", path: "./images/ハイドラント圧.png" },
  { display: "デュアルスイーパー", path: "./images/デュアルスイーパー.png" },
  { display: "R-PEN/5B", path: "./images/R-PEN<replace>5B.png" },
  { display: "14式竹筒銃・甲", path: "./images/14式竹筒銃・甲.png" },
  { display: "R-PEN/5H", path: "./images/R-PEN<replace>5H.png" },
  { display: "ソイチューバー", path: "./images/ソイチューバー.png" },
  { display: "スクイックリンα", path: "./images/スクイックリンα.png" },
  { display: "スプラスコープFRST", path: "./images/スプラスコープFRST.png" },
  { display: "14式竹筒銃・乙", path: "./images/14式竹筒銃・乙.png" },
  { display: "4Kスコープ", path: "./images/4Kスコープ.png" },
  { display: "スプラスコープ", path: "./images/スプラスコープ.png" },
  {
    display: "ソイチューバーカスタム",
    path: "./images/ソイチューバーカスタム.png",
  },
  { display: "4Kスコープカスタム", path: "./images/4Kスコープカスタム.png" },
  { display: "リッター4K", path: "./images/リッター4K.png" },
  { display: "ハイドラント", path: "./images/ハイドラント.png" },
  {
    display: "イグザミナー・ヒュー",
    path: "./images/イグザミナー・ヒュー.png",
  },
  {
    display: "ハイドラントカスタム",
    path: "./images/ハイドラントカスタム.png",
  },
  {
    display: "クーゲルシュライバー",
    path: "./images/クーゲルシュライバー.png",
  },
  { display: "バレルスピナー", path: "./images/バレルスピナー.png" },
  { display: "スクイックリンβ", path: "./images/スクイックリンβ.png" },
  {
    display: "スプラチャージャーコラボ",
    path: "./images/スプラチャージャーコラボ.png",
  },
  { display: "ノーチラス79", path: "./images/ノーチラス79.png" },
  { display: "スプラスピナー", path: "./images/スプラスピナー.png" },
  { display: "リッター4Kカスタム", path: "./images/リッター4Kカスタム.png" },
  { display: "バレルスピナーデコ", path: "./images/バレルスピナーデコ.png" },
  {
    display: "オーダーチャージャー レプリカ",
    path: "./images/オーダーチャージャー レプリカ.png",
  },
  { display: "ノーチラス47", path: "./images/ノーチラス47.png" },
];
